import math


def make_barrel(
    length,
    width,
    base_forward=6.0,
    lateral_offset=0.0,
    angle_offset=0.0,
    cycle_group=0,
    **overrides,
):
    barrel = {
        "length": length,
        "width": width,
        "rear_width": width,
        "front_width": width,
        "base_forward": base_forward,
        "lateral_offset": lateral_offset,
        "angle_offset": angle_offset,
        "cycle_group": cycle_group,
        "muzzle_extra": 8.0,
        "bullet_speed_multiplier": 1.0,
        "bullet_damage_multiplier": 1.0,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 1.0,
        "penetration_bonus": 0,
        "spread": 0.0,
        "recoil_multiplier": 1.0,
    }
    barrel.update(overrides)
    return barrel


TANK_DEFINITIONS = {
    "Basic": {
        "display_name": "Basic",
        "upgrade_level": 15,
        "upgrades": ["Twin", "Sniper", "Machine Gun", "Flank Guard"],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.0,
        "bullet_speed_multiplier": 1.0,
        "bullet_damage_multiplier": 1.0,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 1.0,
        "penetration_bonus": 0,
        "spread": 0.0,
        "recoil_multiplier": 1.0,
        "move_speed_multiplier": 1.0,
        "max_health_multiplier": 1.0,
        "barrels": [make_barrel(50, 18, base_forward=5.0)],
    },
    "Twin": {
        "display_name": "Twin",
        "upgrade_level": 30,
        "upgrades": ["Triple Shot", "Quad Tank", "Twin Flank"],
        "fire_mode": "cycle",
        "reload_multiplier": 0.82,
        "bullet_speed_multiplier": 1.0,
        "bullet_damage_multiplier": 0.95,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 0.95,
        "penetration_bonus": 0,
        "spread": 0.015,
        "recoil_multiplier": 0.95,
        "move_speed_multiplier": 1.0,
        "max_health_multiplier": 1.0,
        "barrels": [
            make_barrel(48, 14, base_forward=6.0, lateral_offset=-10.0, cycle_group=0),
            make_barrel(48, 14, base_forward=6.0, lateral_offset=10.0, cycle_group=1),
        ],
    },
    "Sniper": {
        "display_name": "Sniper",
        "upgrade_level": 30,
        "upgrades": ["Assassin", "Hunter"],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.18,
        "bullet_speed_multiplier": 1.28,
        "bullet_damage_multiplier": 1.12,
        "bullet_life_multiplier": 1.35,
        "bullet_size_multiplier": 1.0,
        "penetration_bonus": 1,
        "spread": 0.0,
        "recoil_multiplier": 1.05,
        "move_speed_multiplier": 0.97,
        "max_health_multiplier": 0.98,
        "barrels": [make_barrel(74, 16, base_forward=6.0)],
    },
    "Machine Gun": {
        "display_name": "Machine Gun",
        "upgrade_level": 30,
        "upgrades": ["Destroyer", "Gunner"],
        "fire_mode": "simultaneous",
        "reload_multiplier": 0.62,
        "bullet_speed_multiplier": 0.94,
        "bullet_damage_multiplier": 0.78,
        "bullet_life_multiplier": 0.95,
        "bullet_size_multiplier": 0.92,
        "penetration_bonus": 0,
        "spread": 0.11,
        "recoil_multiplier": 0.8,
        "move_speed_multiplier": 1.02,
        "max_health_multiplier": 1.0,
        "barrels": [make_barrel(48, 18, base_forward=6.0, rear_width=20, front_width=12)],
    },
    "Flank Guard": {
        "display_name": "Flank Guard",
        "upgrade_level": 30,
        "upgrades": ["Twin Flank", "Quad Tank", "Tri-Angle"],
        "fire_mode": "simultaneous",
        "reload_multiplier": 0.9,
        "bullet_speed_multiplier": 0.98,
        "bullet_damage_multiplier": 0.95,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 0.95,
        "penetration_bonus": 0,
        "spread": 0.01,
        "recoil_multiplier": 0.95,
        "move_speed_multiplier": 1.05,
        "max_health_multiplier": 1.0,
        "barrels": [
            make_barrel(48, 16, base_forward=6.0),
            make_barrel(34, 12, base_forward=3.0, angle_offset=math.pi),
        ],
    },
    "Twin Flank": {
        "display_name": "Twin Flank",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "cycle",
        "reload_multiplier": 0.76,
        "bullet_speed_multiplier": 0.98,
        "bullet_damage_multiplier": 0.92,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 0.92,
        "penetration_bonus": 0,
        "spread": 0.02,
        "recoil_multiplier": 0.92,
        "move_speed_multiplier": 0.98,
        "max_health_multiplier": 1.02,
        "barrels": [
            make_barrel(46, 12, base_forward=6.0, lateral_offset=-10.0, cycle_group=0),
            make_barrel(46, 12, base_forward=6.0, lateral_offset=10.0, cycle_group=1),
            make_barrel(34, 10, base_forward=3.0, lateral_offset=-9.0, angle_offset=math.pi, cycle_group=0),
            make_barrel(34, 10, base_forward=3.0, lateral_offset=9.0, angle_offset=math.pi, cycle_group=1),
        ],
    },
    "Triple Shot": {
        "display_name": "Triple Shot",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.14,
        "bullet_speed_multiplier": 0.97,
        "bullet_damage_multiplier": 0.9,
        "bullet_life_multiplier": 1.0,
        "bullet_size_multiplier": 0.9,
        "penetration_bonus": 0,
        "spread": 0.01,
        "recoil_multiplier": 0.95,
        "move_speed_multiplier": 1.0,
        "max_health_multiplier": 1.02,
        "barrels": [
            make_barrel(46, 13, base_forward=6.0, lateral_offset=-10.0, angle_offset=-0.22),
            make_barrel(52, 15, base_forward=6.0),
            make_barrel(46, 13, base_forward=6.0, lateral_offset=10.0, angle_offset=0.22),
        ],
    },
    "Assassin": {
        "display_name": "Assassin",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.42,
        "bullet_speed_multiplier": 1.52,
        "bullet_damage_multiplier": 1.22,
        "bullet_life_multiplier": 1.75,
        "bullet_size_multiplier": 1.0,
        "penetration_bonus": 2,
        "spread": 0.0,
        "recoil_multiplier": 1.12,
        "move_speed_multiplier": 0.96,
        "max_health_multiplier": 0.96,
        "barrels": [make_barrel(92, 15, base_forward=6.0)],
    },
    "Hunter": {
        "display_name": "Hunter",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "cycle",
        "reload_multiplier": 1.02,
        "bullet_speed_multiplier": 1.24,
        "bullet_damage_multiplier": 1.06,
        "bullet_life_multiplier": 1.48,
        "bullet_size_multiplier": 1.0,
        "penetration_bonus": 1,
        "spread": 0.015,
        "recoil_multiplier": 1.0,
        "move_speed_multiplier": 0.98,
        "max_health_multiplier": 0.98,
        "barrels": [
            make_barrel(78, 14, base_forward=6.0, cycle_group=0, bullet_damage_multiplier=1.1),
            make_barrel(42, 10, base_forward=6.0, cycle_group=1, bullet_damage_multiplier=0.88, bullet_speed_multiplier=1.05),
        ],
    },
    "Gunner": {
        "display_name": "Gunner",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "cycle",
        "reload_multiplier": 0.52,
        "bullet_speed_multiplier": 0.98,
        "bullet_damage_multiplier": 0.65,
        "bullet_life_multiplier": 0.95,
        "bullet_size_multiplier": 0.78,
        "penetration_bonus": 0,
        "spread": 0.07,
        "recoil_multiplier": 0.72,
        "move_speed_multiplier": 0.97,
        "max_health_multiplier": 1.02,
        "barrels": [
            make_barrel(38, 7, base_forward=10.0, lateral_offset=-16.0, cycle_group=0),
            make_barrel(34, 7, base_forward=6.0, lateral_offset=-5.0, cycle_group=0),
            make_barrel(34, 7, base_forward=6.0, lateral_offset=5.0, cycle_group=1),
            make_barrel(38, 7, base_forward=10.0, lateral_offset=16.0, cycle_group=1),
        ],
    },
    "Destroyer": {
        "display_name": "Destroyer",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 2.0,
        "bullet_speed_multiplier": 0.78,
        "bullet_damage_multiplier": 3.8,
        "bullet_life_multiplier": 0.9,
        "bullet_size_multiplier": 1.9,
        "penetration_bonus": 4,
        "spread": 0.02,
        "recoil_multiplier": 1.9,
        "move_speed_multiplier": 0.9,
        "max_health_multiplier": 1.08,
        "barrels": [make_barrel(66, 28, base_forward=6.0)],
    },
    "Tri-Angle": {
        "display_name": "Tri-Angle",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 0.84,
        "bullet_speed_multiplier": 0.96,
        "bullet_damage_multiplier": 0.88,
        "bullet_life_multiplier": 0.98,
        "bullet_size_multiplier": 0.9,
        "penetration_bonus": 0,
        "spread": 0.02,
        "recoil_multiplier": 0.9,
        "move_speed_multiplier": 1.16,
        "max_health_multiplier": 0.98,
        "barrels": [
            make_barrel(48, 15, base_forward=6.0),
            make_barrel(32, 11, base_forward=2.0, angle_offset=math.pi - 0.55),
            make_barrel(32, 11, base_forward=2.0, angle_offset=math.pi + 0.55),
        ],
    },
    "Quad Tank": {
        "display_name": "Quad Tank",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.1,
        "bullet_speed_multiplier": 0.98,
        "bullet_damage_multiplier": 0.88,
        "bullet_life_multiplier": 0.96,
        "bullet_size_multiplier": 0.88,
        "penetration_bonus": 0,
        "spread": 0.01,
        "recoil_multiplier": 0.88,
        "move_speed_multiplier": 0.98,
        "max_health_multiplier": 1.04,
        "barrels": [
            make_barrel(48, 14, base_forward=6.0, angle_offset=0.0),
            make_barrel(38, 11, base_forward=3.0, angle_offset=math.pi / 2),
            make_barrel(38, 11, base_forward=3.0, angle_offset=math.pi),
            make_barrel(38, 11, base_forward=3.0, angle_offset=-math.pi / 2),
        ],
    },
    "Smasher": {
        "display_name": "Smasher",
        "upgrade_level": 45,
        "upgrades": ["Landmine", "Auto Smasher", "Spike"],
        "fire_mode": "simultaneous",
        "reload_multiplier": 999.0,
        "bullet_speed_multiplier": 0.0,
        "bullet_damage_multiplier": 0.0,
        "bullet_life_multiplier": 0.0,
        "bullet_size_multiplier": 0.0,
        "penetration_bonus": 0,
        "spread": 0.0,
        "recoil_multiplier": 0.0,
        "move_speed_multiplier": 1.15,
        "max_health_multiplier": 1.25,
        "barrels": [],
    },
    "Landmine": {
        "display_name": "Landmine",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 999.0,
        "bullet_speed_multiplier": 0.0,
        "bullet_damage_multiplier": 0.0,
        "bullet_life_multiplier": 0.0,
        "bullet_size_multiplier": 0.0,
        "penetration_bonus": 0,
        "spread": 0.0,
        "recoil_multiplier": 0.0,
        "move_speed_multiplier": 1.2,
        "max_health_multiplier": 1.3,
        "barrels": [],
    },
    "Auto Smasher": {
        "display_name": "Auto Smasher",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 1.3,
        "bullet_speed_multiplier": 0.95,
        "bullet_damage_multiplier": 0.85,
        "bullet_life_multiplier": 0.95,
        "bullet_size_multiplier": 0.75,
        "penetration_bonus": 0,
        "spread": 0.03,
        "recoil_multiplier": 0.3,
        "move_speed_multiplier": 1.08,
        "max_health_multiplier": 1.25,
        "barrels": [make_barrel(28, 8, base_forward=6.0)],
    },
    "Spike": {
        "display_name": "Spike",
        "upgrade_level": None,
        "upgrades": [],
        "fire_mode": "simultaneous",
        "reload_multiplier": 999.0,
        "bullet_speed_multiplier": 0.0,
        "bullet_damage_multiplier": 0.0,
        "bullet_life_multiplier": 0.0,
        "bullet_size_multiplier": 0.0,
        "penetration_bonus": 0,
        "spread": 0.0,
        "recoil_multiplier": 0.0,
        "move_speed_multiplier": 1.08,
        "max_health_multiplier": 1.35,
        "barrels": [],
    },
}


OFFICIAL_CLASS_TREE = {
    "Tank": {
        "tier": 1,
        "children": ["Twin", "Sniper", "Machine Gun", "Flank Guard", "Smasher"],
    },
    "Twin": {"tier": 2, "children": ["Triple Shot", "Quad Tank", "Twin Flank"]},
    "Sniper": {"tier": 2, "children": ["Overseer", "Assassin", "Hunter", "Trapper"]},
    "Machine Gun": {"tier": 2, "children": ["Destroyer", "Gunner", "Sprayer"]},
    "Flank Guard": {"tier": 2, "children": ["Twin Flank", "Quad Tank", "Tri-Angle", "Auto 3"]},
    "Smasher": {"tier": 3, "children": ["Landmine", "Auto Smasher", "Spike"]},
    "Triple Shot": {"tier": 3, "children": ["Penta Shot", "Spread Shot", "Triplet"]},
    "Quad Tank": {"tier": 3, "children": ["Octo Tank", "Auto 5"]},
    "Twin Flank": {"tier": 3, "children": ["Triple Twin", "Battleship"]},
    "Overseer": {"tier": 3, "children": ["Overlord", "Manager", "Necromancer", "Overtrapper", "Factory", "Battleship"]},
    "Assassin": {"tier": 3, "children": ["Ranger", "Stalker"]},
    "Hunter": {"tier": 3, "children": ["Predator", "Streamliner"]},
    "Trapper": {"tier": 3, "children": ["Mega Trapper", "Tri-Trapper", "Gunner Trapper", "Auto Trapper"]},
    "Destroyer": {"tier": 3, "children": ["Hybrid", "Annihilator", "Skimmer", "Rocketeer"]},
    "Gunner": {"tier": 3, "children": ["Auto Gunner", "Gunner Trapper", "Streamliner"]},
    "Sprayer": {"tier": 3, "children": []},
    "Tri-Angle": {"tier": 3, "children": ["Booster", "Fighter"]},
    "Auto 3": {"tier": 3, "children": ["Auto 5", "Auto Gunner"]},
    "Penta Shot": {"tier": 4, "children": []},
    "Spread Shot": {"tier": 4, "children": []},
    "Triplet": {"tier": 4, "children": []},
    "Octo Tank": {"tier": 4, "children": []},
    "Auto 5": {"tier": 4, "children": []},
    "Triple Twin": {"tier": 4, "children": []},
    "Battleship": {"tier": 4, "children": []},
    "Overlord": {"tier": 4, "children": []},
    "Manager": {"tier": 4, "children": []},
    "Necromancer": {"tier": 4, "children": []},
    "Overtrapper": {"tier": 4, "children": []},
    "Factory": {"tier": 4, "children": []},
    "Ranger": {"tier": 4, "children": []},
    "Stalker": {"tier": 4, "children": []},
    "Predator": {"tier": 4, "children": []},
    "Streamliner": {"tier": 4, "children": []},
    "Mega Trapper": {"tier": 4, "children": []},
    "Tri-Trapper": {"tier": 4, "children": []},
    "Gunner Trapper": {"tier": 4, "children": []},
    "Auto Trapper": {"tier": 4, "children": []},
    "Hybrid": {"tier": 4, "children": []},
    "Annihilator": {"tier": 4, "children": []},
    "Skimmer": {"tier": 4, "children": []},
    "Rocketeer": {"tier": 4, "children": []},
    "Auto Gunner": {"tier": 4, "children": []},
    "Booster": {"tier": 4, "children": []},
    "Fighter": {"tier": 4, "children": []},
    "Landmine": {"tier": 4, "children": []},
    "Auto Smasher": {"tier": 4, "children": []},
    "Spike": {"tier": 4, "children": []},
}


def get_tank_definition(tank_type):
    return TANK_DEFINITIONS.get(tank_type, TANK_DEFINITIONS["Basic"])


def get_tank_display_name(tank_type):
    return get_tank_definition(tank_type)["display_name"]


def get_barrel_anchor(origin_x, origin_y, tank_angle, barrel, scale=1.0):
    base_forward = barrel.get("base_forward", 6.0) * scale
    lateral_offset = barrel.get("lateral_offset", 0.0) * scale
    side_angle = tank_angle + (math.pi / 2)
    base_x = origin_x + math.cos(tank_angle) * base_forward + math.cos(side_angle) * lateral_offset
    base_y = origin_y + math.sin(tank_angle) * base_forward + math.sin(side_angle) * lateral_offset
    barrel_angle = tank_angle + barrel.get("angle_offset", 0.0)
    return base_x, base_y, barrel_angle


def build_barrel_polygon(origin_x, origin_y, tank_angle, barrel, scale=1.0):
    base_x, base_y, barrel_angle = get_barrel_anchor(origin_x, origin_y, tank_angle, barrel, scale=scale)
    width_scale = 1.18
    rear_half_width = (barrel.get("rear_width", barrel.get("width", 20)) * scale * width_scale) / 2
    front_half_width = (barrel.get("front_width", barrel.get("width", 20)) * scale * width_scale) / 2
    length = barrel.get("length", 50) * scale

    side_angle = barrel_angle + (math.pi / 2)
    tip_x = math.cos(barrel_angle) * length
    tip_y = math.sin(barrel_angle) * length
    rear_side_x = math.cos(side_angle) * rear_half_width
    rear_side_y = math.sin(side_angle) * rear_half_width
    front_side_x = math.cos(side_angle) * front_half_width
    front_side_y = math.sin(side_angle) * front_half_width

    return [
        (base_x + rear_side_x, base_y + rear_side_y),
        (base_x - rear_side_x, base_y - rear_side_y),
        (base_x - front_side_x + tip_x, base_y - front_side_y + tip_y),
        (base_x + front_side_x + tip_x, base_y + front_side_y + tip_y),
    ]
